### ISSUE TITLE
Данные не найдены

### ISSUE THREAD

**Issue by retro-games** [lafin/ru-yts#10]
http://popcorn-time.ru/android/mobile-armeabi-v7a-release-0.1.2.apk

Андроид приложение не подгружает никаких данных. 

Пишет no data found.

**Comment by lafin** [comment]
[Тут](https://github.com/lafin/ru-yts#i-am-not-affiliated-with-the-project-popcorn-timeru) я написал что я никак не связан с проектом popcorn-time.ru
