### ISSUE TITLE
Docker don't run

### ISSUE THREAD

**Issue by BioQwer** [lafin/ru-yts#11]
Hello @lafin !
Firstly, i filled credentials in docker file.
I use your setup manual and docker run has failed with: 
```javascript
module.js:340
    throw err;
          ^
Error: Cannot find module '/var/apps/yts/app.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by lafin** [comment]
You try start the app locally? You are from Russia?
nnm-club.me banned into the Russia now. https://lenta.ru/news/2016/04/11/noname/
But I found the mirror and make some fix. Check that.

**Comment by BioQwer** [comment]
Yes, now i try to start locally. Yes.
I know about this banned this resource.
In logs i see that application work. How can i understand that request's failed? 
Can you add to more error message?

Now i see in error.log .
```
==> error.log <==
[Thu, 14 Apr 2016 08:46:23 GMT] error: E11000 duplicate key error collection: db.items index: title_1_info.quality_1 dup key: { : "Лобстер / The Lobster", : "HDRip" }
[Thu, 14 Apr 2016 08:46:23 GMT] error: E11000 duplicate key error collection: db.items index: title_1_info.quality_1 dup key: { : "Из тьмы / The Hallow", : "HDRip" }
```

What need i check to bootstrap this application?

**Comment by mbgroot** [comment]
it's not exactly a mistake. just in the database already have such a record. the script displays information about data duplication.
