### ISSUE TITLE
Worker stops after error

### ISSUE THREAD

**Issue by albabosh** [lafin/ru-yts#20]
Worker (--only-worker -c 4000) stops after error. How to continue after error ?

**Comment by lafin** [comment]
Nothing. About the 4000, limit 1000 for torrents provider (http://www.torrentino.me/movies?page=1000)

**Comment by mbgroot** [comment]
Оно до 1000 не доходит. Где-то раньше стопится.

**Comment by albabosh** [comment]
Собралось ~6500 штук, кто больше?

**Comment by lafin** [comment]
Solved?

**Comment by mbgroot** [comment]
Пока я экспериментировал, мой IP забанили на торрентино :)
Добавил в requestData и getFilmData прокси, но что-то пока не получается, идёт отвал по таймауту...

**Comment by lafin** [comment]
доэксперементировались. походу стопанули сервер.

**Comment by albabosh** [comment]
Если не по IP, то как ? Сам торрентино работает

**Comment by lafin** [comment]
сейчас да. на момент написания сообшения он несколько часов не работал.
