### ISSUE TITLE
Split worker & api completely

### ISSUE THREAD

**Issue by albabosh** [lafin/ru-yts#22]
I think it is good to split worker & api completely, for someone can run them on 2 machines

**Comment by lafin** [comment]
For what?

**Comment by albabosh** [comment]
Чтобы воркер запустить на 1 машине, а апп - на другой.

**Comment by lafin** [comment]
это я пониманию. зачем Вам такая конфигурация?

**Comment by albabosh** [comment]
Теоретически, воркер могут забанить по IP, воркеров может быть несколько, приложений тоже может быть несколько (для надежности например, и с каждым приложением воркер запускать незачем)
