### ISSUE TITLE
movie_details.json is sometimes required

### ISSUE THREAD

**Issue by cornboy** [lafin/ru-yts#31]
It is good to implement /movie_details.json? endpoint, since some applications need this.

**Comment by lafin** [comment]
@cornboy When this endpoint using?

**Comment by cornboy** [comment]
https://github.com/yify-pop/yify-pop - this thing uses.

**Comment by lafin** [comment]
@cornboy you can make PR for that.

**Comment by cornboy** [comment]
It plays torrent video in browser

**Comment by cornboy** [comment]
Could you tell me what do you mean "PR" ?

**Comment by lafin** [comment]
@cornboy https://help.github.com/articles/about-pull-requests/
