### ISSUE TITLE
Worker don't run

### ISSUE THREAD

**Issue by incorwild** [lafin/ru-yts#34]
<pre>
docker run --rm --link yts_mongo_1:mongo lafin/ru-yts:x86_64 --only-worker -c 5
</pre>

container_linux.go:247: starting container process caused "exec: \"--only-worker\": executable file not found in $PATH"
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"--only-worker\\\": executable file not found in $PATH\"\n".

**Comment by lafin** [comment]
@incorwild please show me ```$ uname -a```

**Comment by incorwild** [comment]
@lafin Docker version 1.12.5, build 7392c3b

**Comment by lafin** [comment]
@incorwild please show me all output 
for me it's
```
$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by incorwild** [comment]
@lafin, I'm updated Docker, but the problem is still relevant.
<pre>$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64
 Experimental: false</pre>

**Comment by lafin** [comment]
@incorwild so strange I not found relevant solution on you problem. I guess data your pc was corrupted. Try manually remove container and recreate. Probably it's solve your problem.

**remove old images, containers, volumes**
```bash
docker rm -f -v $(docker ps -a -q -f status=exited); docker rmi -f $(docker images -q -f dangling=true); docker volume rm -f $(docker volume ls -q -f dangling=true);
```

**remove all images, containers, volumes**
```bash
docker rm -f -v $(docker ps -a -q); docker rmi -f $(docker images -q); docker volume rm -f $(docker volume ls -q);
```

**Comment by incorwild** [comment]
@lafin it's help for me, thanks
