### ISSUE TITLE
Number of questions about running my own API!

### ISSUE THREAD

**Issue by Fazelesswhite** [lafin/ru-yts#9]
Hey, I got the server up and running yaay, but I don't seem to be able to pull any torrents.. Maybe it's because I don't have the credentials to that russian site. Anywho, I'd like to pull torrents from sites like the piratebay or kat, can I do that? Can you guys guide me through it ?

**Comment by lafin** [comment]
This is code can't support grab torrent from any torrent catalogs, specifically for russian torrent server "nnm-club.me" only with russian localised films. For another catalogs need customise parser. This project parsing nnm-club and proxying to Popcorn Time like api (yts).

**Comment by Fazelesswhite** [comment]
How do I make a custom parser?

**Comment by lafin** [comment]
You want add support the TheBroBay for Popcorn Time?

**Comment by Fazelesswhite** [comment]
No no, I want to add support for piratebay..it's more reliable, it will be
a huuuge favor if you could help me

On Fri, Oct 30, 2015 at 4:23 PM, Sergey Kuvakin <notifications@github.com>
wrote:

> You want add support the TheBroBay for Popcorn Time?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lafin/ru-yts/issues/9#issuecomment-152510514>.
>



-- 
Regards,
Hayzam Sherif.
Lead developer and co-founder of TheBroBay. <http://brobay.tk>
E-Mail or I'll be on the IRC/Facebook Chat!

**Comment by lafin** [comment]
Need add authorization on tpb and rewrite parser. Find torrents list, maybe catalog or recent films. Open the film page (https://thepiratebay.uk.net/torrent/12439849/Spy.2015.720p.BRRip.x264-YIFY) and need extract name, year, size, genre, quality. All films include imdb link. You can use imdb link get more information about film.
